### ISSUE TITLE
Heroku - BINA paid account 

### ISSUE THREAD

**Issue by roktiw** [binawork/ktonadaje#13]
Data for registration https://sklejkaiprzyjaciele.pl/strona/kontakt
Add as admin: binaworkfoundation@gmail.com, roktiw@gmail.com

**Comment by kMatejak** [comment]
registered with mail binaworkfoundation@gmail.com and the same password as gmail account; linkt to heroku login page https://id.heroku.com/login

**Comment by roktiw** [comment]
Please assign to me and move on kanbana to testing column
